export const recipeConsts = {
    REQUEST_RECIPE_DATA_PENDING: 'REQUEST_RECIPE_DATA_PENDING',
    REQUEST_RECIPE_DATA_SUCCESS: 'REQUEST_RECIPE_DATA_SUCCESS',
    REQUEST_RECIPE_DATA_BY_ID_PENDING: 'REQUEST_RECIPE_DATA_BY_ID_PENDING',
    REQUEST_RECIPE_DATA_BY_ID_SUCCESS: 'REQUEST_RECIPE_DATA_BY_ID_SUCCESS',
    REQUEST_RECIPE_DATA_BY_AUTHOR: 'REQUEST_RECIPE_DATA_BY_AUTHOR',
    ADD_RECIPE_DATA: 'ADD_RECIPE_DATA',
    UPDATE_STORED_RECIPE_DATA: 'UPDATE_STORED_RECIPE_DATA',
    REMOVE_RECIPE_DATA: 'REMOVE_RECIPE_DATA',
    UPDATE_ACTIVE_RECIPE_DATA: 'UPDATE_ACTIVE_RECIPE_DATA'
};